CREATE DATABASE BETi
GO

USE BETi
GO

CREATE TABLE BET_Usuarios (

	--ID INT NOT NULL IDENTITY(1,1),
	CorreoElectronico VARCHAR(50) NOT NULL,
	Contraseña VARCHAR(128) NOT NULL,
	Saldo MONEY NOT NULL,
	
	CONSTRAINT PKUsuarios PRIMARY KEY(CorreoElectronico, Contraseña),
	CONSTRAINT CKCorreoElectronico CHECK (CorreoElectronico LIKE '%@%.%'),
	CONSTRAINT CKContraseña CHECK (DATALENGTH(Contraseña) > 7)

)
GO

CREATE TABLE BET_Equipos (

	ID CHAR(3) NOT NULL,
	Nombre VARCHAR(20) NOT NULL,
	Ciudad VARCHAR(30) NULL,

	CONSTRAINT PKEquipos PRIMARY KEY(ID)

)
GO

CREATE TABLE BET_Partidos (
	
	ID INT NOT NULL IDENTITY(1,1),
	IDEquipoLocal CHAR(3) NOT NULL,
	IDEquipoVisitante CHAR(3) NOT NULL,
	GolesLocal TINYINT NOT NULL,
	GolesVisitante TINYINT NOT NULL,
	Apostable BIT NOT NULL,
	Finalizado BIT NOT NULL,
	Fecha SMALLDATETIME NULL,

	CONSTRAINT PKPartidos PRIMARY KEY(ID),
	CONSTRAINT FKPartidosEquipoLocal FOREIGN KEY(IDEquipoLocal) REFERENCES BET_Equipos(ID) ON DELETE NO ACTION ON UPDATE CASCADE,
	CONSTRAINT FKPartidosEquipoVisitante FOREIGN KEY(IDEquipoVisitante) REFERENCES BET_Equipos(ID) ON DELETE NO ACTION ON UPDATE CASCADE

)
GO

CREATE TABLE BET_Apuestas (

	ID INT NOT NULL IDENTITY(1,1),
	Tipo VARCHAR(16) NOT NULL,
	Cuota DECIMAL(4,2) NOT NULL,
	CantidadApostada SMALLMONEY NOT NULL,
	Acertada BIT NOT NULL,
	IDPartido INT NOT NULL,
	CorreoUsuario VARCHAR(50) NOT NULL,
	ContraseñaUsuario VARCHAR(128) NOT NULL,
	Resultado CHAR(1) NULL,
	[Over/Under] DECIMAL(2,1) NULL,
	GolesLocal TINYINT NULL,
	GolesVisitante TINYINT NULL,
	
	CONSTRAINT PKApuestas PRIMARY KEY(ID),
	CONSTRAINT FKApuestasPartidos FOREIGN KEY(IDPartido) REFERENCES BET_Partidos(ID) ON DELETE CASCADE ON UPDATE CASCADE,
	--CONSTRAINT FKApuestasUsuarios FOREIGN KEY(CorreoUsuario) REFERENCES BET_Usuarios(CorreoElectronico) ON DELETE NO ACTION ON UPDATE CASCADE
	 
)
GO

CREATE TABLE BET_Movimientos (

	ID INT NOT NULL IDENTITY(1,1),
	CorreoUsuario VARCHAR(50) NOT NULL,
	ContraseñaUsuario VARCHAR(128) NOT NULL,
	Cantidad SMALLMONEY NOT NULL,
	IDApuesta INT NULL,

	CONSTRAINT PKMovimientos PRIMARY KEY(ID),
	--CONSTRAINT FKMovimientosUsuarios FOREIGN KEY(CorreoUsuario) REFERENCES BET_Usuarios(CorreoElectronico) 
	CONSTRAINT FKMovimientosApuestas FOREIGN KEY(IDApuesta) REFERENCES BET_Apuestas(ID) ON DELETE NO ACTION ON UPDATE CASCADE

)